### ISSUE TITLE
tectonic console cert problems

### ISSUE THREAD

**Issue by kersten** [coreos/tectonic-forum#111]
### Tectonic Version 

I think 1.5.6 can't open tectonic console

### Environment

BareMetal

### Expected Behavior

Open tectonic console

### Actual Behavior

Tectonic console container won't start

### Reproduction Steps

Create Ingress

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: tectonic.example.com
  namespace: kube-lego
  annotations:
    kubernetes.io/ingress.class: tectonic
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
      - tectonic.example.com
      secretName: tectonic-tls-secret
  rules:
    - host: tectonic.example.com
      http:
        paths:
          - path: /.well-known/acme-challenge
            backend:
              serviceName: kube-lego-tectonic
              servicePort: 80
```
Rename ```tectonic-tls-secret``` to ```tectonic-tls-secret-old```

Wait for cert.

Recognise that ```kubectl``` doesn't work anymore.

Remove kube-lego ingress.

Failing tectonic console and kubectl with error:

```error: error fetching provider config: Get https://tectonic.example.com/identity/.well-known/openid-configuration: x509: certificate is valid for ingress.local, not tectonic.example.com```

### Other Information

Try to restart tectonic console, after that the container constatly restarts with message:

```Provider config sync still failing, retrying in 2s: Get https://tectonic.example.com/identity/.well-known/openid-configuration: x509: certificate is valid for ingress.local, not tectonic.example.com```

Is the any chance to get back into the system?
