### ISSUE TITLE
Deploy Simple App example on Bare-metal

### ISSUE THREAD

**Issue by khanattlab** [coreos/tectonic-forum#131]
### Tectonic Version 
1.5.6

### Environment
Lab

What hardware/cloud provider/hypervisor is being used with Tectonic?
Baremetal

### Expected Behavior
kubectl get services
External IP assigned

### Actual Behavior
External IP pending

### Reproduction Steps

  1. ...
  2. ...

### Other Information
Is there an example of using Tectonic ingress for the simple application example shown for AWS
as in https://coreos.com/tectonic/docs/latest/tutorials/first-app.html. 
No external IP assigned on the bare-metal deployment.
Looking at some other posts I tried using Tectonic ingress per https://coreos.com/tectonic/docs/latest/admin/ingress.html with backend as the simple-service but probably not doing it right.
Thanks

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by kbrwn** [comment]
@khanattlab Exposing traffic on baremetal clusters is a bit different than when running on a cloud provider such as AWS. Here is a doc on [Tectonic Ingress](https://coreos.com/tectonic/docs/latest/admin/ingress.html) which has the relevant information.

You should be able to modify the `simple-service.yaml` to have a type `NodePort`: 

```
kind: Service
apiVersion: v1
metadata:
  name: simple-service
  namespace: default
spec:
  selector:
    k8s-app: simple
  ports:
  - protocol: TCP
    port: 80
  type: Nodeport
```

 Create an ingress resource for service  `simple-service` : 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  annotations:
    kubernetes.io/ingress.class: "tectonic"
spec:
  rules:
    - host: hello.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: simple-service
              servicePort: 80
```
