### ISSUE TITLE
Prometheus k8s failing to start, makes hyperkube give up

### ISSUE THREAD

**Issue by deed02392** [coreos/tectonic-forum#160]
### Tectonic Version 
tectonic-1.6.4-tectonic.1
### Environment
darwin
What hardware/cloud provider/hypervisor is being used with Tectonic?
VMWare ESXi 6.5
### Expected Behavior
prometheus-k8s starts
### Actual Behavior
It fails to start and hyperkube gives up, causing entire terraform operation to fail
### Reproduction Steps

  1. Configure a basic 3 node cluster (matchbox, controller, worker)
  2. Manually pxe boot and provision the controller and worker
  3. worker and controller bootstrap successfully up to the point of prometheus failing to come out of 'pending'

### Other Information
I have tried this several times and the steps are repeatable with reliability.

**Comment by deed02392** [comment]
Found an error in journalctl output:

`bash[2740]: [  436.464281] hyperkube[5]: error: unable to recognize "monitoring/prometheus-k8s-service-monitor-apiserver.yaml": no matches for monitoring.coreos.com/, Kind=ServiceMonitor`

The file contains the following:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
  namespace: tectonic-system
  labels:
    k8s-app: apiserver
spec:
  jobLabel: component
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: https
    interval: 30s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
