### ISSUE TITLE
Hostpath mounts a tmpfs instead of rootfs

### ISSUE THREAD

**Issue by fforootd** [coreos/tectonic-forum#167]
### Tectonic Version 

Tectonic 1.5.7-tectonic.1
Kubernetes 1.5.7+tectonic.1

### Environment

Baremetal installation on top of VMware VM's

### Expected Behavior

hostpath should mount the hostpath into a container.

### Actual Behavior

hostpath does mount a tmpfs volume with 7.9GB into the containers

### Reproduction Steps

  1. Create a Pod with a mounted hostpath
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/test/florian
```

  2. Exec a `df -h` in the running pod
This gives something like

![image](https://user-images.githubusercontent.com/9879976/28285531-6d050522-6b35-11e7-8615-7b1eaca39ff7.png)

### Other Information

If we do the same on a GKE Cluster we get the IMHO correct mapping.
![image](https://user-images.githubusercontent.com/9879976/28285562-881e5c14-6b35-11e7-84e4-02c30b4c108c.png)
