### ISSUE TITLE
nginx-ingress-controller authorization fails

### ISSUE THREAD

**Issue by hapnermw** [coreos/tectonic-forum#169]
### Tectonic Version 
1.6.4-tectonic.1

### Environment
AWS

What hardware/cloud provider/hypervisor is being used with Tectonic?
Vanilla AWS Tectonic install with GUI installer of a 3/3 cluster on t2.medium instances

### Expected Behavior
nginx-ingress-controller access to default-http-backend in same namespace should work.

### Actual Behavior
Access is denied

I0801 08:34:33.682661       5 launch.go:96] &{NGINX 0.9.0-beta.3 git-3dd7461 git@github.com:ixdy/kubernetes-ingress.git}
I0801 08:34:33.682687       5 launch.go:99] Watching for ingress class: faucet
I0801 08:34:33.682896       5 launch.go:245] Creating API server client for https://10.3.0.1:443
I0801 08:34:33.683636       5 nginx.go:127] starting NGINX process...
F0801 08:34:33.721825       5 launch.go:113] no service with name faucet/default-http-backend found: the server does not allow access to the requested resource (get services default-http-backend)

### Reproduction Steps

####create a faucet namespace
```
kind: Namespace
apiVersion: v1
metadata:
  name: faucet
  labels:
    app: faucet.tenant
spec:
  finalizers:
    - kubernetes
```
####create a default-http-backend deployment
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: faucet.default-http-backend
  namespace: faucet
  labels:
    k8s-app: default-http-backend
    app: faucet.tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: default-http-backend
      app: faucet.tenant
  template:
    metadata:
      name: default-http-backend
      labels:
        k8s-app: default-http-backend
        app: faucet.tenant
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        # Any image is permissable as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
```
####create a default-http-backend service
```
kind: Service
apiVersion: v1
metadata:
  name: faucet-default-http-backend
  namespace: faucet
  labels:
    k8s-app: default-http-backend
    app: faucet.tenant
spec:
  selector:
    k8s-app: default-http-backend
    app: faucet.tenant
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

####create an nginx-ingress-controller deployment
 ```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faucet.nginx-ingress-controller
  namespace: faucet
  labels:
    k8s-app: nginx-ingress-controller
    app: faucet.tenant
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
        app: faucet.tenant
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nginx-ingress-controller
          image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.3
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 18080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 18080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          args:
            - /nginx-ingress-controller
            - --default-backend-service=faucet/default-http-backend
            - --default-ssl-certificate=faucet/faucet.tls
            - --ingress-class=faucet
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: tls-dhparam-vol
              mountPath: /etc/nginx-ssl/dhparam
              readOnly: true
            - name: nginx-template-volume
              mountPath: /etc/nginx/template
              readOnly: true
      volumes:
        - name: tls-dhparam-vol
          secret:
            secretName: faucet.dhparam
        - name: nginx-template-volume
          configMap:
            name: faucet.nginx-template
            items:
            - key: nginx.tmpl
              path: nginx.tmpl
```
### Other Information
This seems to be a well known issue with much discussion about what component of k8s infrastructure should be granted what access. Unfortunately, I've not found anything that actually resolves this issue.

I would think that something as common as creating a vanilla deployment of the nginx-ingress-controller should work out-of-the-box and not require some arcane understanding of kubernetes internal component authorization.

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
