### ISSUE TITLE
Tectonic Sandbox won't start (behind a proxy)

### ISSUE THREAD

**Issue by DevOpsCow** [coreos/tectonic-forum#185]
### Tectonic Version 
tectonic-sandbox-1.7.1-tectonic.2

### Environment
Tried on Ubuntu 16.04.3 with:
Vagrant 1.9.7
virtualbox-5.1_5.1.26-117224-Ubuntu-trusty_amd64

And on Windows 10 with:
Vagrant 1.9.8
VirtualBox-5.1.26-117224-Win

Both machines are behind a corporate firewall/proxy.
Proxy was enabled on the command line (export/set HTTP_PROXY and HTTPS_PROXY), vagrant was able to install ignite successfully.

What hardware/cloud provider/hypervisor is being used with Tectonic?
Baremetal / Sandbox

### Expected Behavior
Sandbox should start or complete setup.

### Actual Behavior
Vagrant up command dies on setting up the 'c1' machine.
Error from Vagrant is the same in Win10 and Ubuntu16:
```
==> c1: Running provisioner: shell...
    c1: Running: inline script
==> c1: Job for etcd-member.service failed because the control process exited with error code.
==> c1: See "systemctl  status etcd-member.service" and "journalctl  -xe" for details.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Reproduction Steps

  1. Install pre-requisites (Vagrant and Virtualbox)
  2. Set Proxy variables so Vagrant is able to install ignite plugin. (export in Linux, set in windows)
  3. Download tectonic sandbox `tectonic-sandbox-1.7.1-tectonic.2`, unzip it. (following sandbox instructions), and cd into the folder.
  4. Execute `vagrant up --provider=virtualbox` as described in the tectonic sandbox web page.
  5. Wait for the error to come up :)

### Other Information
The machine 'w1' seems to complete fine, its the 'c1' that returns the error.
Vagrant does not supply a more detailed error, or the script file name that causes it.
Both machines stay up, in the login screen. (when looking at those in the Virtualbox console)

**Comment by kbrwn** [comment]
Pretty sure that setting HTTP_PROXY and HTTPS_PROXY is not a sufficient way to pass proxy configuration to vagrant virtual machines. You could try a plugin like [vagrant-proxy-conf](http://tmatilai.github.io/vagrant-proxyconf/).

**Comment by thoslin** [comment]
Had the same issue. After installing vagrant-proxy-conf as suggested by @kbrwn . Seeing another error:
```
==> w1: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sed -e 's/\[Service\]/[Service]\nEnvironmentFile=-\/etc\/default\/docker/g' /usr/lib/systemd/system/docker.service > /tmp/docker.service

Stdout from the command:



Stderr from the command:

sed: can't read /usr/lib/systemd/system/docker.service: No such file or directory
```

**Comment by kbrwn** [comment]
@thoslin Not sure where that error is coming from as tectonic-sandbox has no code that references the `sed` command or `/usr/lib/systemd/system/docker.service`.

**Comment by DevOpsCow** [comment]
Good news, fixed it :)  

The problem is the Docker service (and possibly others?) that run inside the Virtualbox VMs, have no proxy settings set. I confirmed the Docker service was unable to pull the images required to run the Kubernetes containers. And variables sent to Vagrant won't be set for the Docker daemon config files.  

**How to fix it and enable Sandbox to run behind a proxy:**  
You'll need to modify the `controller` and `worker` files under the `provisioning` folder of the tectonic sandbox zip file.  
You'll also need to download the `ct` tool from https://github.com/coreos/container-linux-config-transpiler/releases  

1- Modify the `controller.clc` and `worker.clc` to include the proxy settings under `docker.service` (modify the proxy entries as I'm using an example here)  
```
    - name: docker.service
      enable: true
      dropins:
        - name: docker-proxy.conf
          contents: |
            [Service]
            Environment="HTTP_PROXY=http://my-proxy.mydns.com:8080/" "HTTPS_PROXY=http://my-proxy.mydns.com:8081/" "NO_PROXY=127.0.0.1,172.17.4.101,172.17.4.201,c1,w1,my-vm.mydns.com"
```
2-  Modify the `controller.clc` and `worker.clc` to include the proxy for the default environment.  
Please note I'm including both `10-default-env.conf` and `profile.env` files. Not sure if one of those is enough or preferred, please let me know.  
At the end of both files, under 'storage' add these couple of file entries:  
```
storage:
  files:
    - path: /etc/systemd/system.conf.d/10-default-env.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          [Manager]
          DefaultEnvironment=HTTP_PROXY=http://my-proxy.mydns.com:8080 HTTPS_PROXY=http://my-proxy,mydns.com:8081 NO_PROXY=127.0.0.1,172.17.4.101,172.17.4.201,c1,w1,my-vm.mydns.com
    - path: /etc/profile.env
      filesystem: root
      mode: 0644
      contents:
        inline: |
          export HTTP_PROXY=http://my-proxy.mydns.com:8080
          export HTTPS_PROXY=http://my-proxy,mydns.com:8081
          export NO_PROXY=127.0.0.1,172.17.4.101,172.17.4.201,c1,w1,my-vm.mydns.com
```

3- After you have updated both `.clc` files, you need to update the `.ign` files, following the instructions found on the first line of each `.clc` file.
```
Run `ct -pretty -platform vagrant-virtualbox < worker.clc > worker.ign` to regenerate the ignition config
and
Run `ct -pretty -platform vagrant-virtualbox < controller.clc > controller.ign` to regenerate the ignition config
```

After doing those changes, I was able to spin up the Tectonic Sandbox with the default instructions. (e.g. `vagrant up --provider=virtualbox`)  


**Please note:** as mentioned in their install guide, it will take some minutes to complete. I will download several docker images and start spinning up containers in both `c1` and `w1` VMs.  


Hope this helps anyone else trying to setup Tectonic Sandbox behind a proxy :)
