### ISSUE TITLE
Apiserver complete failure on enabling Dynamic Admission Controller

### ISSUE THREAD

**Issue by gdmello** [coreos/tectonic-forum#263]
### Tectonic Version 
1.8.4

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
On prem baremetal, tectonic installed kubernetes 1.8.4 cluster

### Expected Behaviour
After enabling dynamic admission controllers apiserver arguments in the kube apiserver DaemonSet, the control plane should spin up new apiserver pods with no issue.

### Actual Behaviour
After modifying the apiserver daemon set, new apiserver pods are spun up but they error out, after just enough time, that the rolling update of the other pods progresses and all the apiserver pods error out eventually, making the cluster inaccessible via kubectl.

This is the error raised-
```
I0124 21:47:37.684225       7 server.go:114] Version: v1.8.4+coreos.0
I0124 21:47:37.685498       7 plugins.go:101] No cloud provider specified.
I0124 21:47:38.306279       7 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0124 21:47:38.308017       7 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
W0124 21:47:38.309204       7 admission.go:66] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
panic: An admission plugin wants a client cert/key, but they were not provided.
goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubeapiserver/admission.(*PluginInitializer).Initialize(0xc42082f680, 0x9ac6480, 0xc42028ed90)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubeapiserver/admission/initializer.go:199 +0x367
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.PluginInitializers.Initialize(0xc4209aad20, 0x2, 0x2, 0x9ac6480, 0xc42028ed90)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:182 +0x5d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*PluginInitializers).Initialize(0xc4209aad80, 0x9ac6480, 0xc42028ed90)
    <autogenerated>:18 +0x73
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*Plugins).InitPlugin(0xc4201bd1a0, 0xc420a4d0c8, 0x17, 0x0, 0x0, 0x9abe6c0, 0xc4209aad80, 0x9ac5d00, 0xc4201f23d8, 0x0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:157 +0x20c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*Plugins).NewFromPlugins(0xc4201bd1a0, 0xc420221980, 0x8, 0x8, 0x9abe700, 0xc4202f0cc0, 0x9abe6c0, 0xc4209aad80, 0x0, 0xc42082f680, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:131 +0x126
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.(*AdmissionOptions).ApplyTo(0xc4209536b0, 0xc420f35380, 0x9b0a360, 0xc4208511a0, 0xc4209aace0, 0x2, 0x2, 0x9abe800, 0xc4209d7740)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/admission.go:85 +0x455
k8s.io/kubernetes/cmd/kube-apiserver/app.BuildGenericConfig(0xc4208e1400, 0xc4206a1770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420ab8dc0, 0xc420927da0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:471 +0x114a
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServerConfig(0xc4208e1400, 0x0, 0x0, 0xc4206a1770, 0x0, 0x0, 0xc420dff588, 0x4582c0, 0xc420458680, 0x5, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:272 +0xbd
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc4208e1400, 0xc420abd5c0, 0xc420dff848, 0x1, 0x1)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:130 +0x8d
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc4208e1400, 0xc420abd5c0, 0xc420dff928, 0xc420927d10)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:116 +0xfa
main.NewKubeAPIServer.func1(0xc420abd800, 0xc420321200, 0x0, 0x21, 0xc420abd5c0, 0x0, 0xc420abd680)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/kube-apiserver.go:35 +0x34
main.(*HyperKube).Run(0xc4206a80c0, 0xc420090010, 0x21, 0x21, 0xc420abd5c0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:193 +0x408
main.(*HyperKube).RunToExit(0xc4206a80c0, 0xc420090000, 0x23, 0x24)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:205 +0x57
main.main()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:53 +0x758

```

I’ve had no issue enabling the same flag in minikube, provisioned with kubeadm, so I’m assuming this is related to tectonic.

### Reproduction Steps

  1. Add GenericAdmissionWebhook to admission-control flag of the apiserver in the apiserver DaemonSet.

**Comment by kbrwn** [comment]
@gdmello can you share the exact string you passed to the kube-apiserver daemonset?

**Comment by gdmello** [comment]
@kbrwn - Sure, here is the exact string-
```
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,GenericAdmissionWebhook
```

**Comment by gdmello** [comment]
@kbrwn - If it helps, here are all the flags to the apiserver in the DaemonSet-
```
containers:
  - command:
    - /usr/bin/flock
    - /var/lock/api-server.lock
    - /hyperkube
    - apiserver
    - --runtime-config=""
    - --bind-address=0.0.0.0
    - --secure-port=443
    - --insecure-port=0
    - --advertise-address=0.0.0.0
    - --etcd-servers=https://srv-etcd1.k8s.host.com:2379,https://srv-etcd2.k8s.host.com:2379,https://srv-etcd3.k8s.host.com:2379,https://srv-etcd4.k8s.host.com:2379,https://srv-etcd5.k8s.host.com:2379
    - --etcd-cafile=/etc/kubernetes/secrets/etcd-client-ca.crt
    - --etcd-certfile=/etc/kubernetes/secrets/etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/secrets/etcd-client.key
    - --etcd-quorum-read=true
    - --storage-backend=etcd3
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/16
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,GenericAdmissionWebhook
    - --tls-ca-file=/etc/kubernetes/secrets/ca.crt
    - --tls-cert-file=/etc/kubernetes/secrets/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/secrets/apiserver.key
    - --kubelet-client-certificate=/etc/kubernetes/secrets/apiserver.crt
    - --kubelet-client-key=/etc/kubernetes/secrets/apiserver.key
    - --service-account-key-file=/etc/kubernetes/secrets/service-account.pub
    - --client-ca-file=/etc/kubernetes/secrets/ca.crt
    - --authorization-mode=RBAC
    - --anonymous-auth=false
    - --oidc-issuer-url=https://srv.host.com/identity
    - --oidc-client-id=tectonic-kubectl
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
    - --oidc-ca-file=/etc/kubernetes/secrets/oidc-ca.crt
    - --cloud-provider=
    - --audit-log-path=/var/log/kubernetes/kube-apiserver-audit.log
    - --audit-log-maxage=30
    - --audit-log-maxbackup=3
    - --audit-log-maxsize=100
    image: quay.io/coreos/hyperkube:v1.8.4_coreos.0   
```
