### ISSUE TITLE
Exposing a service using tectonic-ingress

### ISSUE THREAD

**Issue by eugene-chow** [coreos/tectonic-forum#27]
### Tectonic Version 
1.4.7

### Environment
CoreOS on KVM hosts, on-prem installation

### Expected Behavior
`curl -k -H "Host: microbot" https://<worker_IP>` should display `microbot`'s page

### Actual Behavior
`curl -k -H "Host: microbot" https://<worker_IP>` displays `tectonic-console`

### Reproduction Steps

1. Deployed simple app at this [tutorial](https://medium.com/@rothgar/exposing-services-using-ingress-with-on-prem-kubernetes-clusters-f413d87b6d34#.bx4505kjw), with the intention to load-balance it using the ingress controller `tectonic-ingress`.
1. Created deployment using `kubectl run microbot --image=dontrebootme/microbot:v1 --port=80`
1. Exposed deployment using `kubectl expose deployment microbot --port=80 --target-port=80 --type=NodePort`
1. Edited `tectonic-ingress` with `kubectl --namespace=tectonic-system edit ing tectonic-ingress` and added:
    ```
      - host: microbot
        http:
          paths:
          - backend:
              serviceName: microbot
              servicePort: 80
            path: /
    ```

### Other Information

I would like to load-balance over HTTPS similar to what `tectonic-ingress` is doing for `tectonic-console`, but I haven't managed to find such documentation.

Is modifying `tectonic-ingress` the right way to expose a Service on the worker node? Otherwise, what is the recommended way to do so?

Thanks!

**Comment by ericchiang** [comment]
I think `https://` may use TLS SNI. So you may need to use `curl -k https://microbot` then add the correct DNS records internally.

Secondly, I'd advice setting up your own ingress controller and not using `tectonic-ingress`. That's an internal implementation that is likely to change (it has in the past) between releases, has a lot of things custom to Tectonic (e.g. we plan on branding the 503 page) and in general we don't advise users modify `tectonic-system` components.

**Comment by eugene-chow** [comment]
Is there a tutorial for setting up an ingress, but for a Tectonic installation?

I tried these tutorials:
- https://medium.com/@rothgar/exposing-services-using-ingress-with-on-prem-kubernetes-clusters-f413d87b6d34#.db7dc5la3 <https://medium.com/@rothgar/exposing-services-using-ingress-with-on-prem-kubernetes-clusters-f413d87b6d34#.db7dc5la3>
- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx <https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx>

The issue I’m facing is that the tectonic-lb and the tutorial’s ingress conflicts. If I setup the ingress on port 80, any HTTP request to the worker node redirects me to tectonic-console. I think this has something to do with default-http-backend.

If I set up the ingress on port 8080, I can’t access the exposed deployment. Logs in either ingress don’t show anything.

**Comment by dghubble** [comment]
The actual behavior described is expected. Tectonic includes an ingess controller daemonset (bare-metal) and ingress rules for Tectonic identity and the console. Avoid modifying components within the tectonic-system namespace.

On bare-metal, the Tectonic Ingress controller binds host ports for an easy out of box setup which only requires knowledge of adding a DNS entry pointing to workers. Only one such ingress is able to do this. Its less sophisticated and we have plans to add an advanced mode for users with control over their routing layer, which does not make use of host ports.

You could do this now if you are able. Create your own ingress controller in your own namespace with a service of type ClusterIP and a fixed service IP within the Kubernetes service range. Configure static routes or BGP on your router to point to any cluster node as the next hop. For each FQDN served by services on the cluster add a DNS record mapping to the ClusterIP. Depending on your choice of Ingress controller, you'll need to apply an RBAC policy to allow access to the ingress rules listing and secrets.

You could also expose Ingress via a node port, but again, you'd need to configure a router or load balancer to forward 80/443 traffic to the special port. This approach is less flexible.

Running ingress controllers with clusterIPs is preferred on bare-metal, but its not yet consumable to many folks since it requires the knowledge and ability to configure an external router or LB. I expect to write more extensive docs for this in future.

**Comment by eugene-chow** [comment]
Pardon my ignorance. I’m still very new to the terminology used in k8s.
> You could do this now if you are able. Create your own ingress controller in your own namespace with a service of type ClusterIP and a fixed service IP within the Kubernetes service range. Configure static routes or BGP on your router to point to any cluster node as the next hop.
> 
Let’s say I have 3 worker nodes with the IPs - 192.168.100.10, 192.168.100.11, 192.168.100.12 - on the bare metal host. In the last phrase above, do you mean to point the router to these IPs? From what I understand a ClusterIP is an internal IP in the SERVICE_IP_RANGE [here](https://coreos.com/kubernetes/docs/latest/getting-started.html <https://coreos.com/kubernetes/docs/latest/getting-started.html>). I presume you mean that the router has to be made aware of the k8s service IP range (ie. 10.3.0.0/24 in the above coreos.com link).
> You could also expose Ingress via a node port, but again, you'd need to configure a router or load balancer to forward 80/443 traffic to the special port. This approach is less flexible.
> 
This is the solution that I was in fact trying out. However, In this [tutorial](https://medium.com/@rothgar/exposing-services-using-ingress-with-on-prem-kubernetes-clusters-f413d87b6d34#.db7dc5la3 <https://medium.com/@rothgar/exposing-services-using-ingress-with-on-prem-kubernetes-clusters-f413d87b6d34#.db7dc5la3>), I configured it to listen on 8080 instead of 80. However, the traefik ingress doesn’t forward the HTTP packets to the desired service and thus deployment. I couldn’t figure out what was going on, but I suspect that `tectonic-lb` might have interfered with its operation.
> Running ingress controllers with clusterIPs is preferred on bare-metal, but its not yet consumable to many folks since it requires the knowledge and ability to configure an external router or LB. I expect to write more extensive docs for this in future.
> 
I certainly don’t mind trying this approach and writing the docs after that. But I need guidance to understand how this works under the hood before I can proceed.


Thanks for the help! :)

**Comment by mfburnett** [comment]
cc @dghubble @kbrwn

**Comment by dghubble** [comment]
Yes, add a static route for the Ingress clusterIP (or for the service range) and point to any Kubernetes node(s) (not just workers). In bare-metal environments, its assumed you'll be assigning IPs statically to NICs.

Designing bare-metal and AWS Ingress for Tectonic, I explored Traefik for a while. It doesn't yet support TLS ingress resources (the feature list is misleading, manual configuration is different). I'd recommend the Nginx Ingress controller.

I don't recommend you use NodePort here. Most of the blog posts on these topics are for cloud environments. The right Ingress solution on Google Cloud and AWS are different.

**Comment by stevesloka** [comment]
I'm trying the same thing now on our tectonic cluster. What I'm seeing is the route for the console `/` seems to overwrite all other requests. Spinning up another ingress controller doesn't help since it picks up the same ingress resources. 

If I point a wildcard dns to my hosts (e.g. *.mysite.company.com), then I should be able to create an ingress resource of `myapp` and point correctly? 

Here's an example of my ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: fooingress
spec:
  rules:
  - host: myapp.mysite.company.com
    http:
      paths:
      - path: 
        backend:
          serviceName: myservice
          servicePort: 80
```

**Comment by InAnimaTe** [comment]
Wouldn't the Ingress of the tectonic dashboard need to be modified to listen on a different path? Of course, you configure it other ways like to be tied to a NodePort or something.

Here's the piece of what my Ingress for `tectonic-ingress` looks like:

```
spec:
  tls:
    - secretName: tectonic-tls-secret
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: tectonic-console
              servicePort: 80
          - path: /identity
            backend:
              serviceName: tectonic-identity
              servicePort: 5556
```

Just my 2c on this: I think the tectonic console/dashboard/UI should exist as a NodePort. Keeping 80/443 open for people to start from the get-go with any Ingress Controller they want. In my mind, we should give them the tools they need to do awesome work and get out of their way.

**Comment by andyjac** [comment]
I am also struggling with the same issue. I've followed your instructions so far but am still a bit confused.

> For each FQDN served by services on the cluster add a DNS record mapping to the ClusterIP

I am assuming you are talking about configuring DNS within the cluster and not on an external router/load balancer? Also, what constitutes a FQDN in this context and how does one go about adding a DNS mapping within the cluster.

Please forgive any ignorance on my part.

**Comment by InAnimaTe** [comment]
I drew out how the present tectonic console/identity ingress jazz all works. From what I'm seeing, looks as though you should be able to swap out their ingress controller and swap in another (i.e. nginx) relatively easily. You'll need to update/replace  the `tectonic-lb` service which tells internal cluster services how to get to identity and console. Going to attack this. Hopefully I don't break the world and go to bed crying.

![tectonic-ingress](https://cloud.githubusercontent.com/assets/1192726/23243109/c48256e0-f94a-11e6-848a-068b9adfcbbe.jpg)

**Comment by eugene-chow** [comment]
Sorry for the late update. I couldn't get a multi-ingress setup to work in Tectonic (partly because I was n00b) so I gave up and built a k8s from scratch. For those who haven't tried building from scratch, I strongly suggest doing so to better understand how various parts of k8s work together.

@InAnimaTe I tried modifying `tectonic-lb`'s deployment but messed it up sufficiently that I had to fix it in `etcd`. I discourage modifying it because its config is volatile. @ericchiang said:
> I'd advice setting up your own ingress controller and not using tectonic-ingress. That's an internal implementation that is likely to change (it has in the past) between releases, has a lot of things custom to Tectonic (e.g. we plan on branding the 503 page) and in general we don't advise users modify tectonic-system components. 

Instead, try to run a [multi-ingress setup](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/multiple-ingress-controllers). I didn't try this method because I've since torn down my Tectonic cluster.

After exploring k8s in depth, I finally understood what @dghubble meant by:
> add a static route for the Ingress clusterIP (or for the service range) and point to any Kubernetes node(s) you like (not necessarily workers) .

This isn't a practical solution for me, because I want the ingress to be exposed on the worker node's IP (ie. `curl https://worker_node_IP/` returns me the page).

Good luck guys!

**Comment by andyjac** [comment]
@eugene-chow out of curiosity, what walkthrough did you use to build k8s from scratch? I may end up going that route as well.

**Comment by InAnimaTe** [comment]
^I'd also be interested. A little tired of peeling back tectonic components to get the desired functionality. I'm thinking of just using Rancher to get a cluster up and going; probably one of the fastest ways I've seen.

Regarding multi-ingress, I suppose just editing the tectonic daemonset or doing nodeselectors to get it to only live on certain hosts would help you then deploy your own which could sit on the other hosts. Still kind of gross and tricky territory though. @eugene-chow were you actually messing with the `tectonic-lb` service or the `tectonic-ingress-controller`?

@andyjac @eugene-chow I'm `@mario` in the kubernetes slack; I'd love to chat with you guys more on this ;)

**Comment by stevesloka** [comment]
Where I'm struggling with the idea of multiple controllers is (regardless of the port mappings), the controllers are all going to listen to all ingress resources right? So even if I get a new controller setup on a NodePort say, then it's still going to write the tectonic ingress resources to itself as well.

**Comment by robszumski** [comment]
@stevesloka Each ingress controller can be passed a namespace to listen to, this is the best way to isolate them. You can use the downward API to fetch this dynamically:

```
spec:
      containers:
        - name: nginx-ingress-lb
          image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.1
          args:
          - /nginx-ingress-controller
          - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
          - --configmap=$(POD_NAMESPACE)/production-ingress-conf
          - --watch-namespace=$(POD_NAMESPACE)
```

**Comment by stevesloka** [comment]
@robszumski Sweet, that's helpful to test a single namespace. Ideally, what I want is a single Ingress controller for all my namespaces. Or least in this case, all BUT the tectonic-system one. I'll keep poking around unless someone else can clarify this a bit more. Thanks!

**Comment by robszumski** [comment]
@stevesloka sounds good. As a thought exercise, here's some reasons to keep them separate, aka have each team/app manage their own. I'm envisioning a cluster with multiple apps/users/teams:

 - fine-grained version control. for example, I am using a beta version above.
 - customize the default backend service per app
 - separate log streams (this can leak info to unrelated folks)
 - use a customized nginx conf

On the flip side, it's pretty magical to consume ingress if someone else has already set it up :)

**Comment by eugene-chow** [comment]
@andyjac @InAnimaTe sorry for the tardiness. This is the tutorial I followed https://github.com/kelseyhightower/kubernetes-the-hard-way. I tweaked it for an on-prem setup on bare-metal. I highly^10 recommend doing the tutorial. It will be a struggle but you'll also learn a lot of the magic that happens under the hood.

@InAnimaTe I believe I mucked around with the `tectonic-ingress-controller`. It's either the RC or the Deployment, and not the Service.

**Comment by InAnimaTe** [comment]
I ended up just doing this simple quick fix (see below). After trying to run on a different port of kill the daemonset completely and loading the dashboard, directly, it seems like with redirects etc.. it would involve changing a lot more. Instead, merely running the tectonic-ingress-controller on only hosts I define is helpful and doesn't see any breakage, which leaves other hosts open for my own ingress controller.


1. Set label on host you want tectonic ingress controller running on.
2. Update yaml for daemonset adding:
```
      nodeSelector:
        io.tectonic.ingress.enable: 'true'
```
3. Any pods running on hosts without that label should be killed. Edit your DNS entry for "tectonic-workers" to only include A records for the hosts you gave that label.

**Comment by InAnimaTe** [comment]
Building on my previous post, I've since completely eliminated the need for the tectonic-ingress-controller and now exclusively utilize the latest nginx-ingress-controller to serve the tectonic-console.

The real only modifications were to the `tectonic-ingress` Ingress for nginx to properly pick it up.

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: tectonic-ingress
  namespace: tectonic-system
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    ingress.kubernetes.io/whitelist-source-range: '10.1.2.0/24'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - tectonic-worker.example.io
      secretName: tectonic-tls-secret
  rules:
    - host: tectonic-worker.example.io
      http:
        paths:
          - path: /
            backend:
              serviceName: tectonic-console
              servicePort: 80
          - path: /identity
            backend:
              serviceName: tectonic-identity
              servicePort: 5556
```

> Note that I'm running `nginx-ingress-controller` as a DaemonSet to ensure I can access from multiple hosts, just as the tectonic-ingress-controller is setup.

Additionally, a few things to keep in mind:

* As posted before, you could change the URL's specified at install time and reload the manifests to configure tectonic components to work on something else. I'm not doing that at present. Of course you would change DNS and the Ingress rule above (see `host(s)`).
* In my setup, the certificate presented by nginx is the correct one (`tectonic-tls-secret`). If the domain you plan on accessing is publicly reachable, I highly recommend utilizing something like kube-lego and actually getting a valid certificate.
* In terms of security, as you can probably tell, I whitelist only internal IP's for my setup. In addition to using a valid certificate, `nginx-ingress-controller` also has support for [auth](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#authentication) which I recommend using, especially if this is publicly accessible.
* I highly recommend backing up everything in the `tectonic-system` namespace before going and blindly making changes. You could also just verify you have your `assets/tectonic` directory in-tact which has all the manifests you'd need.
