### ISSUE TITLE
403 talking to k8s API using Service Account Token Secret

### ISSUE THREAD

**Issue by cvallance** [coreos/tectonic-forum#42]
### Tectonic Version 

1.5.2-tectonic.1

### Environment

AWS

### Expected Behavior

Expected to get a response when making calls to the k8s RO service API

### Actual Behavior

Getting a 403 forbidden response

### Reproduction Steps

  1. Create pod
  2. Use `KUBERNETES_SERVICE_HOST` & `KUBERNETES_SERVICE_PORT` environment variables to establish the RO k8s service API address
  3. Read `/var/run/secrets/kubernetes.io/serviceaccount/token` file to get the token required to call k8s service API
  4. Make a call to the k8s service API with the token from step 3, e.g. `https://KUBERNETES_SERVICE_HOST:KUBERNETES_SERVICE_PORT/api/v1/pods?page=1`

### Other Information

When I look in the `/var/run/secrets/kubernetes.io/serviceaccount/` folder I can see the `token` file and it does contain what appears to be a valid token. The directory also includes a `ca.crt` file... should I be using this?

This is in node using the https://www.npmjs.com/package/node-kubernetes-client package... could be a bug in there but I've had it working on simple bare k8s deployments (i.e. without tectonic).

**Comment by ericchiang** [comment]
Which namespace are you running in? Tectonic enables RBAC, requiring you to explicitly allow pods to hit the API. See https://coreos.com/tectonic/docs/latest/admin/user-management.html#managing-in-cluster-api-access

**Comment by cvallance** [comment]
Default namespace - will checkout docs

**Comment by cvallance** [comment]
@ericchiang  Ok, so my understanding is that I need to add a role binding to the default service account for the pod.

Can I attach the `readonly` cluster role that Tectonic created? Is that in the default namespace? I.e. could I do the following...

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: default-service-account
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  namespace: default
  name: readonly
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

**Comment by cvallance** [comment]
@ericchiang Ok... so I did the following and I can see them in the system, I blew away the pods and they got recreated but I'm still getting a forbidden response.

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
```

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
