### ISSUE TITLE
In Docs, better describe how to setup your own Ingress on 80/443

### ISSUE THREAD

**Issue by pgburt** [coreos/tectonic-forum#47]
### Desired Feature

In docs, make it clearer how to setup your own Ingress. 

### Other Information

From a customer on IRC: 

> the proxy command gets me to the api, but not the tectonic console

> i guess my ask here is if the tectonic-console is a daemonset that runs on all workers, how am i supposed to run my own ingress controller on 80/443 without disabling it?

> yeah i think a tut on making the tectonic-console only avail through kubectl proxy or more securely accessing it through other means would be really useful.

> sorry when i say tectonic-console i mean the tectonic dashboard/ui

**Comment by mfburnett** [comment]
thanks @pgburt - adding this to our docs queue!

**Comment by pgburt** [comment]
StackPoint Cloud have some good docs, worth taking inspiration from here:
https://stackpointcloud.com/community/tutorial/configure-and-manage-a-kubernetes-haproxy-ingress-controller

**Comment by pgburt** [comment]
Same user asked about this again in IRC:
> hi! tectonic question: if i wanted to free up port 80/443 for my own ingress-controller (currently occupied by the tectonic-ingress-controller), what are the pieces i need to change/be aware of? i have tried tinkering, but always end up breaking the console/authentication.

**Comment by dghubble** [comment]
I've written about how Tectonic Ingress works on another issue [here](https://github.com/coreos/tectonic-forum/issues/27#issuecomment-274916394) if you didn't see that yet.

**Comment by robszumski** [comment]
@dghubble intersted to see what you think about this IRL. I think I agree with these users that we should be using the non-standard ports and let them use 80/443.

**Comment by dghubble** [comment]
Starting with Tectonic 1.5.5-tectonic.3, the Tectonic Ingress Controller can be used for user applications as well. Simply create an Ingress resource for a service using the `kubernetes.io/ingress.class` annotation.

See https://coreos.com/tectonic/docs/latest/admin/ingress.html

**Comment by kcronin** [comment]
Hi, just to confirm - this implies that user-created ingress and backend services must also live in the tectonic-system namespace, is that correct?

**Comment by dghubble** [comment]
Nope, you can create them in any namespace.

**Comment by igoratencompass** [comment]
I use 1.5.5-tectonic.3 and tried the following ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "tectonic"
spec:
  tls:
  - hosts:
    - my-app-tectonic.mydomain.com
    secretName: my-tls-secret
  rules:
  - host: my-app-tectonic.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-app
          servicePort: 80
```

I can't see a new ALB being created for the service ... or my expectation is wrong?

**Comment by dghubble** [comment]
That's the wrong expectation. Tectonic AWS already has an ELB which routes traffic to your Ingress controller, which de-multiplexes HTTP/HTTPS requests based on the hosts in your Ingress manifest. Just add a DNS record which resolves `my-app-tectonic.mydomain.com` to that ELB.

You're referring to the GKE/AWS integrations that provision an ELB on your behalf for each Kubernetes service of type LoadBalancer. That feature is still enabled, though its often overkill.

**Comment by igoratencompass** [comment]
Thanks for the reply @dghubble , however I updated the question with some logs and since the `tectonic-ingress-controller` can not find the service end-points I can't see how can this work.

Also there have been 3 ELB's created by Tectonic: tectonic-api-internal, tectonic-api-external and tectonic-console. Which one does the `tectonic-ingress-controller` use? (if any)

**Comment by igoratencompass** [comment]
By the way, I tried creating `nginx-ingress-controller` in same way as I have done in a k8s cluster created with Kops but the `ingress-nginx` could not start:

```
NAME                                    READY     STATUS             RESTARTS   AGE
ingress-nginx-3737565091-rllh0          0/1       CrashLoopBackOff   9          26m
nginx-default-backend-623339674-sjblc   1/1       Running            0          26m
```

and that is with or without `hostNetwork: true`:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ingress-nginx
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-nginx
        k8s-addon: ingress-nginx.addons.k8s.io
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.3
        name: ingress-nginx
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/nginx-default-backend
        - --configmap=$(POD_NAMESPACE)/ingress-nginx
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx
```
