### ISSUE TITLE
Traefik ingress controller in default namespace cannot reach kubernetes API

### ISSUE THREAD

**Issue by andyjac** [coreos/tectonic-forum#49]
### Tectonic Version 
1.5.2

### Environment
CoreOS on Baremetal

### Expected Behavior
Traefik ingress controller should be able to start in the default namespace

### Actual Behavior
Pod that is created shows the following error:

```
time="2017-02-14T05:44:35Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://10.3.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 403 GET \"https://10.3.0.1:443/apis/extensions/v1beta1/ingresses\": \"Forbidden: \\\"/apis/extensions/v1beta1/ingresses\\\"\", retrying in 3.448165321s"
```

### Reproduction Steps
  1. Spin up new tectonic cluster following [this](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html) walkthrough.
  2. Create a [traefik ingress controller](https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik.yaml) in the default namespace
  3. Examine the logs of the resulting pod that is created

### Other Information
Similar to the user in issue #27, I have been trying to find a way to use my own ingress controller within a Tectonic cluster. Conflicts with the existing `tectonic-ingress` controller led me to try to create my own ingress controller in the default namespace. 

The Tectonic cluster *does* have a `default` serviceaccount and the traefik ingress controller *does* appear to be using a valid `default-token`.

More information, in general, would be appreciated as to how to create new ingress controllers without disrupting the existing Tectonic infrastructure which allows for use of the ui-console among other things.

For reference, [here](https://gist.github.com/andyjac/b8b92468e01791f4bc57a736bdcf5304) is the exact file I am using to deploy the traefik ingress controller.

**Comment by mfburnett** [comment]
Hey @andyjac, thanks for filing this issue. I'll let @ivancherepov take it from here; he should be able to get back to you within a few days and will pull in any other members of our team as needed.

**Comment by IvanCherepov** [comment]
This is related to RBAC rules. Check out "Managing in-cluster API access" section in https://coreos.com/tectonic/docs/latest/admin/user-management.html. It it's not enough, you'll have to extend set of permissions depending on what your ingress controller requires. If you want to set full permission, here is an example

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata: 
  name: admin-service-account
roleRef: 
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  name: admin
subjects: 
  - 
    kind: ServiceAccount
    name: default
    namespace: <YOUR_NAMESPACE_HERE>
```

cc @Quentin-M
