### ISSUE TITLE
Cannot connect with client-go 

### ISSUE THREAD

**Issue by vasu1124** [coreos/tectonic-forum#99]
### Tectonic Version 
1.5.5
### Environment
AWS
### Steps to reproduce
I have setup a tectonics cluster on AWS and downloaded the kubeconfig file from the dashboard.
the config looks like the following and works like a charm with kubetctl:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://myurl:443
  name: tectonic
contexts:
- context:
    cluster: tectonic
    user: tectonic-oidc
  name: tectonic
current-context: tectonic
kind: Config
preferences: {}
users:
- name: tectonic-oidc
  user:
    auth-provider:
      name: "oidc"
      config:
        client-id: tectonic-kubectl
        client-secret: <data>
        id-token: <data>
        idp-certificate-authority-data: <data>
        idp-issuer-url: https://myurl/identity
        refresh-token:  <data>
```

Now, when I try to connect with a go program from outside
```
func main() {
	kubeconfig := flag.String("kubeconfig", "config-tectonic.yaml", "absolute path to the kubeconfig file")
	flag.Parse()

	cfg, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		log.Printf("Error configuring the Kube client (%s)", err)
		panic(err.Error())
	}

	cl, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		log.Printf("Error creating a new Kube client (%s)", err)
		os.Exit(1)
	}
...
```

I get an error `No Auth Provider found for name "oidc"` in `cl, err := kubernetes.NewForConfig(cfg)`.

I would have expected the standard login procedure to also work with the auth provider oidc. 
Well, at least kubectl is doing something additional to work properly and I can't find it documented prominently. Maybe this issue is only a documentation issue ...
